"""Policy observation and action encoding — mirror internal/game/policy.go."""

OBS_SIZE = 40
HIDDEN_SIZE = 128
VALUE_HIDDEN = 64
MAX_OPPONENTS = 3
HAND_SIZE = 4

POLICY_ACT_DRAW_DECK = 0
POLICY_ACT_DRAW_DISCARD = 1
POLICY_ACT_SWAP_BASE = 2
POLICY_ACT_DISCARD = 6
POLICY_ACT_PEEK_OWN_BASE = 7
POLICY_ACT_PEEK_OPP_BASE = 11
POLICY_ACT_SWITCH_BASE = 15
POLICY_ACT_CALL_CAMBIO = 19
POLICY_ACT_DECLINE_SW = 20
POLICY_ACT_SNAP_BASE = 21
POLICY_ACT_STACK_OPP_BASE = 25
POLICY_ACT_STACK_GIVE_BASE = 37
NUM_ACTIONS = 41

STACK_MEMORY_MIN = 0.35
